### ISSUE TITLE
Empty query

### ISSUE THREAD

**Issue by mikebutts** [simonblakemore/my_jammming#1]
https://github.com/simonblakemore/my_jammming/blob/cd1d4cbd869782cd29d544a773f739f6ac6695d4/src/util/Spotify.js#L28

Might be a good idea to add

	if(!searchTerm) {
	  return [];
	}

just as a failsafe

**Comment by simonblakemore** [comment]
Solved but added if statement to .search(term) in App.js to avoid Type Error
`  search(term) {
    if(!term) {
      return;
    }

    Spotify.search(term).then(searchResults => {
      this.setState({searchResults: searchResults});
    });
  }`

**Comment by simonblakemore** [comment]
Solved by adding if statement to .search(term) in App.js to avoid Type Error


```
search(term) {
    if(!term) {
      return;
    }

    Spotify.search(term).then(searchResults => {
    this.setState({searchResults: searchResults});
    });
}
```
